# Generated by Django 4.1.1 on 2022-11-07 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_userprofile_address_line1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='pin_code',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
